# Generated by Django 2.1.7 on 2019-06-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECES1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etudiants',
            new_name='Etudiant',
        ),
    ]
