# Generated by Django 2.1.7 on 2019-06-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECES1', '0002_auto_20190611_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etudiant',
            new_name='Etudiants',
        ),
    ]
