# Generated by Django 2.1.7 on 2019-06-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECES1', '0003_auto_20190611_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etudiants',
            new_name='Etudiant',
        ),
    ]
